
name: Betonvalue Surebets to Telegram

on:
  schedule:
    - cron: "*/15 * * * *"  # Hər 15 dəqiqədə
  workflow_dispatch:

jobs:
  send_surebets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install requests beautifulsoup4 pyTelegramBotAPI
      - name: Run bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          BETONVALUE_USERNAME: ${{ secrets.BETONVALUE_USERNAME }}
          BETONVALUE_PASSWORD: ${{ secrets.BETONVALUE_PASSWORD }}
        run: python main.py
