name: Betonvalue Surebet Checker

on:
  schedule:
    - cron: '*/30 * * * *'  # Hər 30 dəqiqədən bir işə düşəcək
  workflow_dispatch:        # Manual olaraq da başlada bilərsən

jobs:
  check-surebets:
    runs-on: ubuntu-latest

    steps:
    - name: Kodları yüklə
      uses: actions/checkout@v3

    - name: Python quraşdır
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Python asılılıqları quraşdır
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Surebet yoxla
      run: |
        python main.py
